apiVersion: deployments.pds.io/v1
kind: Postgresql
metadata:
  labels:
    name: pg-demo
    namespace: pds-prod
    pds/deployment-id: 491d2da3-67b5-49a4-9c1d-4a9cc0ced759
    pds/deployment-name: pg-demo2
    pds/environment: pds-prod
    pds/project-id: fd53fa1a-eb68-4d39-98ae-e2cf12dd8ed2
  name: pg-demo
  namespace: pds-prod
spec:
  configuration:
    PG_DATABASE: pds
  dnsZone: sales-staging.pds-dns.io
  image: docker.io/portworx/pds-postgresql
  imageBuild: 8c5a18d
  initialize: Once
  nodes: 1
  resources:
    limits:
      cpu: "2"
      memory: 4G
    requests:
      cpu: "1"
      memory: 2G
      storage: 100G
  serviceType: LoadBalancer
  storageClass:
    provisioner: pxd.portworx.com
  storageOptions:
    filesystem: xfs
    forceSpread: "false"
    replicas: "2"
    secure: "false"
  tlsEnabled: false
  tlsIssuer: ""
  version: 14.6-8c5a18d
  versionName: "14.6"

