#apiVersion: "v1"
#kind: "PersistentVolumeClaim"
#metadata: 
#  name: "mongodb-pvc"
#  namespace: "pxbbq"
#  labels: 
#    app: "mongo-db"
#    pxmigrate: "true" 
#spec: 
#  accessModes: 
#    - ReadWriteMany
#  resources: 
#    requests: 
#      storage: 5Gi
#  storageClassName: px-db
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  namespace: pxbbq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mongo
        image: mongo:6.0.3
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: porxie
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "porxie"
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data-dir
          mountPath: /data/db
      volumes:
      - name: mongo-data-dir
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  namespace: pxbbq
spec:
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
