apiVersion: v1
items:
- apiVersion: deployments.pds.io/v1
  kind: Mongodb
  metadata:
    labels:
      name: mdb01
      namespace: pxbbq
      #pds/deployment-id: 01838802-2963-4811-9524-be1cf860a858
      pds/deployment-name: mdb01
      pds/environment: pxbbq
      #pds/project-id: ef41cd33-3726-4392-b068-a54978daade9
    name: mdb-ex01-zvsn17
    namespace: pxbbq
  spec:
    dnsZone: sales-prod.pds-dns.io
    image: docker.io/portworx/pds-mongodb
    imageBuild: c43b0e4
    initialize: Once
    nodes: 2
    resources:
      limits:
        cpu: "2"
        memory: 4G
      requests:
        cpu: "1"
        memory: 2G
        storage: 100G
    serviceType: ClusterIP
    storageClass:
      provisioner: pxd.portworx.com
    storageOptions:
      filesystem: ext4
      forceSpread: "false"
      replicas: "2"
      secure: "false"
    tlsEnabled: false
    tlsIssuer: ""
    version: 6.0.3-c43b0e4
    versionName: 6.0.3
kind: List
metadata:
  resourceVersion: ""
