name: Deploy PR Branch

on: 
  push: 
    branches-ignore:
      - master
jobs:
  build:
    name: deploy from main
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: update namespace
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
            .targets.dev.namespace = "${{ github.ref_name }}"
            ' 'prEnv.yml'
      - name: update namespace2
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '
            .metadata.name = "${{ github.ref_name }}"
            ' 'pxbbq-demo/namespace.yml'
      - name: Deployment
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"
          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/prEnv.yaml" # Path to the deployment file. For more information, see the Create a deployment file section.
          
          
